---
- name: install mysql
  host: localhost
  becomr: true


- name: install mysql
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-community-devel*
    - mysql-community-server*
    - MySQL-python

- name: enable mysql
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: get root password
    shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
    register: root_password

- name: update expired root user password
    command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root.password }}';"

- name: create mysql client user

  mysql_user:
    login_user: root
    login_password: "{{ mysql.root.password }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    host: '%'

  with_items:
    - "{{ mysql.users }}"
